apiVersion: v1
kind: Service
metadata:
  name: task-manager-api
  labels:
    app: task-manager-api
    component: api
spec:
  type: ClusterIP
  selector:
    app: task-manager-api
  ports:
    - name: http
      port: 3000
      targetPort: 3000
