apiVersion: v1
kind: Service
metadata:
  name: policy-claims-api
  labels:
    app: policy-claims-api
    component: api
spec:
  type: NodePort
  selector:
    app: policy-claims-api
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30080
