apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: task-manager
    component: database
spec:
  selector:
    app: task-manager
    component: database
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
  type: ClusterIP
