apiVersion: v1
kind: Secret
metadata:
  name: policy-claims-secrets
  namespace: policy-claims
type: Opaque
stringData:
  JWT_SECRET: change-me-in-production
  MONGODB_URI: mongodb://mongo:27017/policy-claims
